import Head from "next/head";
import { useState, useEffect } from "react";
import styled from "styled-components";
import Layout from "../components/Layout";

export default function Home() {
  const [logueado, setLoagueado] = useState(false);

  useEffect(() => {
    setLoagueado(true);
  }, []);

  return (
    <>
      <Head>
        <title>Discuss Robertfrontend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1 className="">
          Discuss with <span style={{ color: "#6c5ce7" }}>RobertFrontend</span>
        </h1>
        <Content>
          {logueado ? (
            <ContentUser>
              <h4>
                Bienvenido <span>name</span>, ¡encantado de conocerte!
              </h4>
              <div className="form">
                <label>Nuevo Mensaje</label>
                <input
                  type="text"
                  placeholder="nuevo mensaje..."
                  className="d-block"
                />
                <button>Enviar</button>
              </div>
              <div className="discuss mt-4">
                <h4>Mensajes</h4>
                <div className="card p-2">
                  <h5>Descripcion del mensaje klk</h5>
                  <p>By: @fulanodetal</p>
                </div>
              </div>
            </ContentUser>
          ) : (
            "noo"
          )}
        </Content>
      </Layout>
    </>
  );
}
const Content = styled.div`
  width: 100%;
  min-height: 100vh;
  background-color: #dfe6e9;
  padding: 2em;
  border-radius: 8px;
  color: #2d3436;
`;
const ContentUser = styled.div`
  .form {
    margin-top: 1.5em;
    label {
      font-size: 1.2em;
      padding-bottom: 5px;
    }
    input {
      width: 100%;
      outline: none;
      border: 2px solid #6c5ce77a;
      padding: 0.5em 1em;
      border-radius: 5px;
      &:focus {
        border: 2px solid #6c5ce7;
      }
    }
    button {
      background-color: #6c5ce7;
      border: none;
      padding: 0.4em 2em;
      color: white;
      font-weight: 500;
      border-radius: 4px;
      margin-top: 10px;
      cursor: pointer;
    }
  }
`;
